# Generated by Django 2.1 on 2018-11-01 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todoentry',
            name='priority',
            field=models.CharField(choices=[('1', '긴급'), ('2', '중요한 일'), ('3', '평범한 일'), ('4', '사소한 일')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='todoentry',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
