# Generated by Django 2.1 on 2018-11-04 07:50

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20181101_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', '마감기한이 지난 할일 목록'), ('2', '이벤트성 알림')], max_length=1)),
                ('detail', models.TextField(blank=True)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelManagers(
            name='todoentry',
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
